### Remaking facet plots with updated information (i.e. we can plot the graphs without transforming them)

# Clean up environment and load in packages

rm(list = ls())

library(dplyr)
library(tidyr)
library(drcte)
library(ggplot2)

# The basis of this comes from this tutorial https://www.statforbiology.com/2022/stat_drcte_6-ht1step/
# Summarizes how to use cumulative proportion of germinated seeds as data points, and curves generated by the model as curves to plot


### Load in and clean up data ###################################################

FH_long <-read.csv("F-hallii-rows_Long-format.csv")
FC_long <-read.csv("F-camp-rows_Long-format.csv")

head(FH_long)
head(FC_long)

## F. hallii data =============================================================##

# Convert columns to factors so the model can properly incorporate them
FH_long <- FH_long %>%
  mutate(across(1:6, factor))

# Trim and condense data frame -------------------------------------------------#

# Select only the columns we need for the plot
FH_trimmed <- FH_long %>%
  dplyr::select(Species, Length, Temperature, Moisture, timeBef, timeAf, count, propCum)

# Check number of rows per treatment combo

FH_trimmed %>%
  group_by(Length, Temperature, Moisture, timeAf) %>%
  summarise(count = n()
  ) %>%
  ungroup()
#> This shows that we have 3 replicates for each treatment combination, which will
#> show up as separate groups when we try to plot the data. We need to average 
#> these rows so we only have one row per treatment combo

# Average the count and propCum values across replicates of the same treatment

FH_averaged <- FH_trimmed %>%
  group_by(Length, Temperature, Moisture, timeBef, timeAf) %>%
  summarise(
    count = mean(count),
    propCum = mean(propCum)
  ) %>%
  ungroup()  # Remove grouping

FH_averaged # dataframe which has averaged the value of propCum across identical treatments

# Check to see if groups have been collapsed
FH_averaged %>%
  group_by(Length, Temperature, Moisture, timeAf) %>%
  summarise(count = n())
#> Each treatment combination now only has one instance in the data

# Create a TtE model from which we can source our plot curves ------------------#

FH.TtE <- drmte(count ~ timeBef + timeAf,
                   fct = loglogistic(),
                   data = FH_averaged,
                   curveid = Temperature:Length:Moisture)

summary(FH.TtE) 

# Isolate treatment groups -----------------------------------------------------#

# Isolate only the groups we want to plot (treatment groups)
FH_trt_groups <- subset(FH_averaged, Temperature %in% c("FR", "MF", "DF") & 
                            Length %in% c("1M", "3M", "5M"))

FH_trt_groups$Moisture <- as.character(FH_trt_groups$Moisture) 
#> This converts the Moisture levels in FH_trt_groups to characters (rather than factors)
#> to make sure that the legend colours match the lines on the plot

# Set the correct order for the labels
FH_trt_groups$Temperature <- factor(FH_trt_groups$Temperature, levels = c("FR", "MF", "DF"))

# Pull curve-plotting data from our model --------------------------------------#
FHcurves <- plotData(FH.TtE) # Pulls curve data from the model

#> Because the model is a 3-way interaction, FHcurves only lists plotting data 
#> for a combined "Temp:Length:Moisture" category. We need to separate it into 
#> the individual factors so we can call on those factors in our plot
FHcurves$plotFits <- separate(FHcurves$plotFits, "Temperature:Length:Moisture", 
                              into = c("Temperature", "Length", "Moisture"), sep = ":")

# Isolate curve data for just our treatment groups of interest
FH_select_curves <- FHcurves$plotFits %>%
  filter(Temperature %in% c("FR", "MF", "DF") & 
           Length %in% c("1M", "3M", "5M"))

# Set the correct order for the labels
FH_select_curves$Temperature <- factor(FH_select_curves$Temperature, levels = c("FR", "MF", "DF"))

# Isolate control data for comparison ------------------------------------------#

control_points_FH <- subset(FH_averaged, Temperature == "RT" & Length == "C" & Moisture == "NS")

control_curve_FH <- FHcurves$plotFits %>%
  filter(Temperature == "RT" & Length == "C" & Moisture == "NS")

# Add the control curve data to every facet combination in order to plot properly (TBH I do not know exactly what this is doing. Trying to add in the control curve in other ways was resulting in a separate "Control" facet within the grid, so this is a solution GPT came up with. It may be overcomplicating things, but it works)
control_points_expanded_FH <- expand.grid(Temperature = unique(FH_trt_groups$Temperature),
                                          Length = unique(FH_trt_groups$Length)) %>%
  merge(control_points_FH, by = NULL)

control_curve_expanded_FH <- expand.grid(Temperature = unique(FH_select_curves$Temperature),
                                         Length = unique(FH_select_curves$Length)) %>% 
  merge(control_curve_FH, by = NULL)


## F. campestris data ==========================================================##

# Convert columns to factors so the model can properly incorporate them
FC_long <- FC_long %>%
  mutate(across(1:6, factor))

# Trim and condense data frame -------------------------------------------------#

# Select only the columns we need for the plot
FC_trimmed <- FC_long %>%
  dplyr::select(Species, Length, Temperature, Moisture, timeBef, timeAf, count, propCum)

# Check number of rows per treatment combo
FC_trimmed %>%
  group_by(Length, Temperature, Moisture, timeAf) %>%
  summarise(count = n()) %>%
  ungroup()

#> This shows that we have 3 replicates for each treatment combination, which will
#> show up as separate groups when we try to plot the data. We need to average 
#> these rows so we only have one row per treatment combo.

# Average the count and propCum values across replicates of the same treatment
FC_averaged <- FC_trimmed %>%
  group_by(Length, Temperature, Moisture, timeBef, timeAf) %>%
  summarise(
    count = mean(count),
    propCum = mean(propCum)
  ) %>%
  ungroup()  # Remove grouping

# Check to see if groups have been collapsed
FC_averaged %>%
  group_by(Length, Temperature, Moisture, timeAf) %>%
  summarise(count = n())
#> Each treatment combination now only has one instance in the data

#> Time travel! We're going to remove groups from our data that cause NA values in our
#> model fit, before we fit our model. (We found these groups by fitting the model first)

FC_averaged <- FC_averaged %>%
  filter(!(Temperature == "DF" & Length == "1M" & Moisture == "PO") &
           !(Temperature == "FR" & Length == "5M" & Moisture == "PR") &
           !(Temperature == "MF" & Length == "3M" & Moisture == "PR"))

# Create a TtE model from which we can source our plot curves ------------------#

FC.TtE <- drmte(count ~ timeBef + timeAf,
                fct = loglogistic(),
                data = FC_averaged,
                curveid = Temperature:Length:Moisture,
                separate = TRUE) 
#> Use separate =TRUE for our FC data to avoid errors with the fit
#> It may still show an error message, but it does fit the model

summary(FC.TtE) 
#> Removing the problematic groups from the raw data in the above step means we no 
#> longer have NA values in our model summary

# Isolate treatment groups -----------------------------------------------------#

# Isolate only the groups we want to plot (treatment groups)
FC_trt_groups <- subset(FC_averaged, Temperature %in% c("FR", "MF", "DF") & 
                          Length %in% c("1M", "3M", "5M"))

FC_trt_groups$Moisture <- as.character(FC_trt_groups$Moisture) 
#> This converts the Moisture levels in FC_trt_groups to characters (rather than factors)
#> to make sure that the legend colours match the lines on the plot

# Set the correct order for the labels
FC_trt_groups$Temperature <- factor(FC_trt_groups$Temperature, levels = c("FR", "MF", "DF"))

# Pull curve-plotting data from our model --------------------------------------#
FCcurves <- plotData(FC.TtE) # Pulls curve data from the model

#> Because the model is a 3-way interaction, FCcurves only lists plotting data 
#> for a combined "Temp:Length:Moisture" category. We need to separate it into 
#> the individual factors so we can call on those factors in our plot
FCcurves$plotFits <- separate(FCcurves$plotFits, "Temperature:Length:Moisture", 
                              into = c("Temperature", "Length", "Moisture"), sep = ":")

# Isolate curve data for just our treatment groups of interest
FC_select_curves <- FCcurves$plotFits %>%
  filter(Temperature %in% c("FR", "MF", "DF") & 
           Length %in% c("1M", "3M", "5M"))

# Set the correct order for the labels
FC_select_curves$Temperature <- factor(FC_select_curves$Temperature, levels = c("FR", "MF", "DF"))

# Isolate control data for comparison ------------------------------------------#

control_points_FC <- subset(FC_averaged, Temperature == "RT" & Length == "C" & Moisture == "NS")

control_curve_FC <- FCcurves$plotFits %>%
  filter(Temperature == "RT" & Length == "C" & Moisture == "NS")

# Add the control curve data to every facet combination in order to plot properly 
control_points_expanded_FC <- expand.grid(Temperature = unique(FC_trt_groups$Temperature),
                                          Length = unique(FC_trt_groups$Length)) %>%
  merge(control_points_FC, by = NULL)

control_curve_expanded_FC <- expand.grid(Temperature = unique(FC_select_curves$Temperature),
                                         Length = unique(FC_select_curves$Length)) %>% 
  merge(control_curve_FC, by = NULL)

### Making facet plots from our extracted data ##################################

# General labels used for both curves

length_labels <- c("1M" = "1 Month", "3M" = "3 Months", "5M" = "5 Months")

temp_labels <- c("FR" = "Fridge", "MF" = "Moderate Freeze", "DF" = "Deep Freeze")

## F. hallii plots =============================================================#

# Line plot
FH_line_plot <- ggplot(FH_trt_groups, aes(x = timeAf, y = propCum, group = Moisture)) +
  geom_line(data = FH_select_curves, aes(x = timeAf, y = CDF, group = Moisture, color = Moisture), linewidth = 1) +  # Add fitted lines
  geom_line(data = control_curve_expanded_FH, aes(x = timeAf, y = CDF, color = "Control", linetype = "Control"), color = "black", linewidth = 1) +  # Control line
  facet_grid(rows = vars(Temperature), cols = vars(Length), 
             labeller = labeller(Temperature = temp_labels, Length = length_labels)) + 
  scale_x_continuous(name = "Time (days)") +
  scale_y_continuous(name = "Cumulative proportion of germinated seeds",
                     limits = c(0,1)) +
  scale_color_manual(values = c("NS" = "#EDAE49", "PR" = "#00798C", "PO" = "#D1495B"),
                     labels = c("NS" = "No Soak", "PR" = "Pre-Soak", "PO" = "Post-Soak")) +  # Updated colors for Moisture levels 
  scale_linetype_manual(values = "dotdash", guide = guide_legend(title = NULL)) +
  labs(
    title = "Festuca hallii",
    color = "Hydration"  # Title for the color legend (Moisture levels)
  ) +
  guides(
    color = guide_legend(order = 1),  # hydration legend comes first
    linetype = guide_legend(title = NULL, order = 2)  # control legend comes second
  ) +
  theme_grey() +  # Apply grey theme instead of custom colors
  theme(
    axis.title.x = element_text(margin = margin(t = 17), size = rel(1.2), face = "bold"),  # Axis title style
    axis.title.y = element_text(margin = margin(r = 17), size = rel(1.2), face = "bold"),  # Axis title style
    axis.text = element_text(size = rel(1.2)),  # Axis text size
    strip.text = element_text(size = rel(1.2), face = "bold"),  # Strip text properties
    legend.title = element_text(size = rel(1.2), face = "bold"),  # Legend title style
    legend.text = element_text(size = rel(1.2)),  # Legend text style
    legend.background = element_rect(fill = "#FFFFFF"),  # Legend background to default
    plot.margin = margin(20, 20, 20, 30),
    plot.title = element_text(size = rel(1.3), face = "bold.italic")
  )

FH_line_plot

## F. campestris plots =============================================================#
FC_line_plot <- ggplot(FC_trt_groups, aes(x = timeAf, y = propCum, group = Moisture)) +
  geom_line(data = FC_select_curves, aes(x = timeAf, y = CDF, group = Moisture, color = Moisture), linewidth = 1) +  # Add fitted lines
  geom_line(data = control_curve_expanded_FC, aes(x = timeAf, y = CDF, color = "Control", linetype = "Control"), color = "black", linewidth = 1) +  # Control line
  facet_grid(rows = vars(Temperature), cols = vars(Length), 
             labeller = labeller(Temperature = temp_labels, Length = length_labels)) + 
  scale_x_continuous(name = "Time (days)") +
  scale_y_continuous(name = "Cumulative proportion of germinated seeds",
                     limits = c(0,1)) +
  scale_color_manual(values = c("NS" = "#EDAE49", "PR" = "#00798C", "PO" = "#D1495B"),
                     labels = c("NS" = "No Soak", "PR" = "Pre-Soak", "PO" = "Post-Soak")) +  # Updated colors for Moisture levels 
  scale_linetype_manual(values = "dotdash", guide = guide_legend(title = NULL)) +
  labs(
    title = "Festuca campestris",
    color = "Hydration"  # Title for the color legend (Moisture levels)
  ) +
  guides(
    color = guide_legend(order = 1),  # hydration legend comes first
    linetype = guide_legend(title = NULL, order = 2)  # control legend comes second
  ) +
  theme_grey() +  # Apply grey theme instead of custom colors
  theme(
    axis.title.x = element_text(margin = margin(t = 17), size = rel(1.2), face = "bold"),  # Axis title style
    axis.title.y = element_text(margin = margin(r = 17), size = rel(1.2), face = "bold"),  # Axis title style
    axis.text = element_text(size = rel(1.2)),  # Axis text size
    strip.text = element_text(size = rel(1.2), face = "bold"),  # Strip text properties
    legend.title = element_text(size = rel(1.2), face = "bold"),  # Legend title style
    legend.text = element_text(size = rel(1.2)),  # Legend text style
    legend.background = element_rect(fill = "#FFFFFF"),  # Legend background to default
    plot.margin = margin(20, 20, 20, 30),
    plot.title = element_text(size = rel(1.3), face = "bold.italic")
  )

FC_line_plot

### Save plots as high-res PNGs ##################################################

# F hallii
ggsave(filename = "F-hallii_Faceted-TtE-curves_High-Res.png",
               plot = FH_line_plot,  
               width = 10,
               height = 6.35,
               dpi = 300,  # Set higher resolution
               units = "in")
               
ggsave(filename = "F-camp_Faceted-TtE-curves_High-Res.png",
       plot = FC_line_plot,  
       width = 10,
       height = 6.35,
       dpi = 300,  # Set higher resolution
       units = "in")

